FROM node:18
WORKDIR /app
COPY package*.json ./

RUN npm install
RUN npm install -g vite

COPY . .
ENV VITE_BACKEND_URL=https://backend-service-709934480697.europe-west1.run.app
RUN npm run build

EXPOSE 4173

CMD ["vite", "preview", "--host", "0.0.0.0"]
